---

dependencies: []

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Manage directories encrypted with encfs'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.4'

  platforms:

    - name: Ubuntu
      versions:
        - lucid
        - precise
        - quantal
        - raring
        - saucy
        - trusty

    - name: GenericLinux
      versions:
        - all

    - name: Debian
      versions:
        - wheezy
        - jessie

  galaxy_tags:
    - encryption
    - security
    - filesystem
    - fuse
    - encfs
