---

- name: Send password to remote host via passfiles
  template:
    src: '{{ item }}.j2'
    dest: '{{ encfs_passfile + "_" + item }}'
    mode: 0600
  with_items:
    - 'init'
    - 'pass'
  when: ((encfs_is_mounted is defined and encfs_is_mounted.stdout == "") and (encfs_mode is undefined or not encfs_mode)) or
        (encfs_mode is defined and encfs_mode == 'open')

- name: Create encfs encrypted directory with passfiles
  shell: cat {{ encfs_passfile }}_init | encfs {{ encfs }}{{ encfs_suffix }} {{ encfs }} --stdinpass
  args:
    creates: '{{ encfs_config_file }}'
  register: encfs_created

- name: Mount encfs encrypted directory with passfiles
  shell: cat {{ encfs_passfile }}_pass | encfs {{ encfs }}{{ encfs_suffix }} {{ encfs }} --stdinpass
  when: (encfs_created is defined and encfs_created.changed == False) and
        (encfs_is_mounted is undefined or encfs_is_mounted is defined and encfs_is_mounted.stdout == "") and
        (encfs_mode is undefined or (encfs_mode is defined and encfs_mode != 'close'))

- name: Destroy passfiles
  command: shred --remove {{ encfs_passfile }}_init {{ encfs_passfile }}_pass
  args:
    removes: '{{ encfs_passfile }}_init'
  changed_when: False


