---

- name: Create encfs encrypted directory with password
  shell: printf "p\n{{ encfs_password }}\n" | encfs {{ encfs }}{{ encfs_suffix }} {{ encfs }} --stdinpass
  args:
    creates: '{{ encfs_config_file }}'
  register: encfs_created

- name: Mount encfs encrypted directory with password
  shell: printf "{{ encfs_password }}\n" | encfs {{ encfs }}{{ encfs_suffix }} {{ encfs }} --stdinpass
  when: (encfs_created is defined and encfs_created.changed == False) and
        (encfs_is_mounted is undefined or encfs_is_mounted is defined and encfs_is_mounted.stdout == "") and
        (encfs_mode is undefined or (encfs_mode is defined and encfs_mode != 'close'))


