# This is the Plex CFN - May run more templates from here - but most likely leverage Ansible from here on out
AWSTemplateFormatVersion: "2010-09-09"
Description: Plex CloudFormation templates
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: VPC & Network Configuration
      Parameters: [VPCID, SubnetID]
    - Label:
        default: Plex Configuration
      Parameters: [KeyPair, InstanceType, PlexVersion]
    ParameterLabels:
      VPCID:
        default: VPC ID
      SubnetID:
        default: Subnet ID
      InstanceType:
        default: Plex EC2 Instance Type
      PlexVersion:
        default: Plex Version to install
Parameters:
  VPCID:
    Type: List<AWS::EC2::VPC::Id>
  SubnetID:
    Description: SubnetID to deploy Plex
    Type: List<AWS::EC2::Subnet::Id>
  InstanceType:
    Description: Amazon EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues: [t1.micro, t2.micro, t2.small, t2.medium, m1.small, m1.medium,
      m1.large, m1.xlarge, m2.xlarge, m2.2xlarge, m2.4xlarge, m3.medium, m3.large,
      m3.xlarge, m3.2xlarge, m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
      c1.medium, c1.xlarge, c3.large, c3.xlarge, c3.2xlarge, c3.4xlarge, c3.8xlarge,
      c4.large, c4.xlarge, c4.2xlarge, c4.4xlarge, c4.8xlarge, g2.2xlarge, r3.large,
      r3.xlarge, r3.2xlarge, r3.4xlarge, r3.8xlarge, i2.xlarge, i2.2xlarge, i2.4xlarge,
      i2.8xlarge, d2.xlarge, d2.2xlarge, d2.4xlarge, d2.8xlarge, hi1.4xlarge, hs1.8xlarge,
      cr1.8xlarge, cc2.8xlarge, cg1.4xlarge]
    ConstraintDescription: must be a valid EC2 instance type.
  KeyPair:
    Description: Select an SSH Key for the instances. For security reaons you may want to upload your own and select that.
    Type: AWS::EC2::KeyPair::KeyName
  OperatingSystem:
    Type: String
    AllowedValues: [Ubuntu1604, Amazon]
    Default: Amazon
  S3TemplateBucket:
    Type: String
    Description: The name of the S3 Bucket that contains all our template resources
  S3TemplateKey:
    Description: The url for this git package
    Type: String
    Default: "https://github.com/lordmuffin/aws-cfn-plex.git"
  S3TemplateBucketUrl:
    Description: The url for aws buckets
    Type: String
    Default: "https://s3.amazon.com"
  PlexVersion:
    Description: Plex Version to install ex. 1.3.4.3285-b46e0ea
    Type: String
    Default: "1.3.4.3285-b46e0ea"

Resources:
  CredstashStack:
   Type: AWS::CloudFormation::Stack
   Properties:
     TemplateURL: !Sub
       - ${S3Url}/${TemplateBucketName}/${TemplateBucketPrefix}/templates/credstash.cfn.yml
       - {S3Url: !FindInMap [AWSInfoRegionMap, !Ref 'AWS::Region', TemplateBucketS3URL]}
     Parameters:
       ParentStackName: !Ref "AWS::StackName"
       TemplateBucketName: !Ref TemplateBucketName
       TemplateBucketPrefix: !Ref TemplateBucketPrefix
  Plex:
    Type: "AWS::CloudFormation:Stack"
    Properties:
      TemplateURL: !Join [/, 'S3TemplateBucketUrl', !Ref 'S3TemplateBucket', templates/plex.cfn.yml]
        Parameters:
          EnvironmentName: !Ref VPCID
          Subnets: !Ref SubnetID
  #ALB:
  #  Type: "AWS::CloudFormation:Stack"
  #  Properties:
  #    TemplateURL:
  #      Parameters:
  #        EnvironmentName: !Ref VPCID
  #        Subnets: !Ref SubnetID
  #        SecurityGroup:

Outputs:
  VPCID:
    Description: VPC ID
    Value: !Ref VPCID
    Export:
      Name: !Ref VPCID
